-- 1. Create the applications table
CREATE TABLE applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL,
  college TEXT NOT NULL,
  year_of_study TEXT NOT NULL,
  branch TEXT NOT NULL,
  team_name TEXT,
  team_size TEXT,
  experience_level TEXT NOT NULL,
  skills TEXT NOT NULL,
  github_url TEXT,
  linkedin_url TEXT,
  why_join TEXT NOT NULL,
  project_idea TEXT,
  resume_url TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add performance indices
CREATE INDEX idx_applications_status ON applications(status);
CREATE INDEX idx_applications_created_at ON applications(created_at);

-- 3. Create a high-performance stats function for the dashboard
CREATE OR REPLACE FUNCTION get_application_stats()
RETURNS json
LANGUAGE sql
AS $$
  SELECT json_build_object(
    'total', count(*),
    'pending', count(*) FILTER (WHERE status = 'pending'),
    'approved', count(*) FILTER (WHERE status = 'approved'),
    'rejected', count(*) FILTER (WHERE status = 'rejected')
  ) FROM applications;
$$;
